'use strict';
const $=s=>document.querySelector(s), form=$('#create-form');
let state=null,music=[],selected=new Set(),musicLoaded=false,lastJobs='',lastEpisodes='',currentTab='studio';
const statusNames={queued:'Ожидает',running:'В работе',succeeded:'Готово',failed:'Ошибка',interrupted:'Прервано',cancelled:'Отменено'};
const phases={generation:'Генерация музыки',audio:'Проверка и сведение',video:'Монтаж видео',complete:'Готово'};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notify(text){$('#notice').textContent=text;$('#notice').hidden=false;}
async function api(path,payload){const res=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(res.status===401)throw Error('Нужен вход. Обнови страницу и введи логин/пароль.');const data=await res.json();if(!res.ok)throw Error(data.error||'Ошибка запроса');return data;}
function tab(id){currentTab=id;document.querySelectorAll('.tab').forEach(n=>n.hidden=n.id!==id);document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('active',n.dataset.tab===id));if(id==='music')loadMusic();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function options(select,items,chosen){select.replaceChildren();Object.entries(items).forEach(([v,p])=>{const n=node('option',p.label);n.value=v;select.append(n);});select.value=chosen;}
function updateForm(){const isLibrary=form.elements.mode.value==='library',audio=form.elements.format.value==='audio';$('#library-pick').hidden=!isLibrary;$('#musical-card').style.opacity=isLibrary?'.5':'1';for(const key of ['style','mood','bpm','custom_prompt','track_min','track_max'])form.elements[key].disabled=isLibrary;form.elements.time_of_day.disabled=audio;form.elements.width.disabled=audio;if(state){const p=state.presets.styles[form.elements.style.value];$('#style-hint').textContent=p.tested?'Проверен на нашей системе.':'Экспериментальный пресет — первый результат стоит прослушать.';}}
for(const key of ['mode','format','style'])form.elements[key].onchange=updateForm;
$('#open-library').onclick=()=>tab('music');
function selectedCount(){$('#selection-count').textContent=`Выбрано: ${selected.size}`;$('#use-selection').textContent=`Использовать выбранные (${selected.size})`;}
$('#use-selection').onclick=()=>{form.elements.mode.value='library';updateForm();tab('studio');};
form.onsubmit=async e=>{e.preventDefault();$('#submit').disabled=true;try{const value=k=>form.elements[k].value;const p={title:value('title'),mode:value('mode'),minutes:Number(value('minutes')),style:value('style'),mood:value('mood'),time_of_day:value('time_of_day'),width:Number(value('width')),track_min:Number(value('track_min')),track_max:Number(value('track_max')),crossfade:Number(value('crossfade')),bpm:value('bpm')?Number(value('bpm')):null,custom_prompt:value('custom_prompt'),audio_only:value('format')==='audio',selected:[...selected]};await api('/api/jobs',p);notify('Выпуск добавлен в очередь. Браузер можно закрыть.');tab('queue');await refresh();}catch(e){notify(e.message);}finally{$('#submit').disabled=false;}};
$('#pause').onclick=async()=>{try{await api('/api/queue',{paused:!state.paused});await refresh();}catch(e){notify(e.message);}};
function button(text,fn,cls='secondary'){const b=node('button',text,cls);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){notify(e.message);}finally{b.disabled=false;}};return b;}
function renderJobs(){const key=JSON.stringify(state.jobs);if(key===lastJobs)return;lastJobs=key;const opened=new Set([...document.querySelectorAll('#jobs details[open]')].map(n=>n.dataset.id));const parent=$('#jobs');parent.replaceChildren();if(!state.jobs.length){parent.append(node('div','Здесь появятся твои выпуски. Создай первый во вкладке «Создать выпуск».','empty'));return;}for(const j of state.jobs){const card=node('article',undefined,'card'),head=node('div',undefined,'job-head');head.append(node('div',j.title,'job-title'),node('span',statusNames[j.status]||j.status,'badge '+j.status));card.append(head);const p=j.payload;card.append(node('p',`${p.minutes} мин · ${state.presets.styles[p.style].label} · ${p.audio_only?'Только музыка':state.presets.scenes[p.time_of_day].label} · ${new Date(j.created*1000).toLocaleString()}`,'job-meta'));if(j.status==='running')card.append(node('p',phases[j.phase.stage]||'Подготовка задачи'));if(j.error)card.append(node('p',j.error,'hint'));if(j.log){const details=node('details'),summary=node('summary','Журнал');details.dataset.id=j.id;details.open=opened.has(j.id);details.append(summary,node('pre',j.log));card.append(details);}const actions=node('div',undefined,'job-actions');if(j.status==='queued')actions.append(button('Отменить',async()=>{await api('/api/job-action',{id:j.id,action:'cancel'});await refresh();}));if(['failed','interrupted'].includes(j.status))actions.append(button('Повторить',async()=>{if(!confirm('Перед повтором проверь, что старая генерация ACE-Step завершилась, либо перезапусти сервер ACE-Step. Подтверждаешь, что старой активной генерации нет?'))return;await api('/api/job-action',{id:j.id,action:'retry',confirmed:true});notify('Задача возвращена в очередь. Нажми «Продолжить очередь», когда будешь готов.');await refresh();}));if(j.status==='succeeded')actions.append(button('Открыть выпуски',()=>tab('episodes')));card.append(actions);parent.append(card);}}
async function loadMusic(){try{music=await api('/api/music');musicLoaded=true;const allowed=new Set(music.filter(t=>!t.excluded).map(t=>t.sha));selected=new Set([...selected].filter(id=>allowed.has(id)));renderMusic();}catch(e){notify(e.message);}}
function visibleMusic(){const q=$('#search').value.toLowerCase();return music.filter(t=>t.title.toLowerCase().includes(q)&&(!$('#favorites').checked||t.favorite));}
function trackDate(t){const d=new Date(t.created_at*1000);if(!Number.isFinite(d.getTime()))return 'Дата неизвестна';return (t.date_kind==='generation'?'Создан: ':'Дата файла: ')+new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d);}
function renderMusic(){const parent=$('#tracks');parent.replaceChildren();const rows=visibleMusic();if(!rows.length)parent.append(node('div','Треков пока нет. Сгенерируй выпуск или импортируй готовую очередь командой lofi collect.','empty'));for(const t of rows){const row=node('div',undefined,'track'+(t.excluded?' excluded':'')),check=node('input');check.type='checkbox';check.checked=selected.has(t.sha);check.disabled=t.excluded;check.onchange=()=>{if(check.checked)selected.add(t.sha);else selected.delete(t.sha);selectedCount();};const body=node('div');body.append(node('div',t.title,'track-title'),node('div',trackDate(t),'hint'),node('div',`${t.seconds?t.seconds+' сек · ':''}seed ${t.seed??'—'}`,'hint'));const audio=node('audio');audio.controls=true;audio.preload='none';audio.src='/media/music/'+t.sha;body.append(audio);const controls=node('div',undefined,'track-controls');const pref=async(favorite,excluded)=>{await api('/api/preference',{sha:t.sha,favorite,excluded});await loadMusic();};controls.append(button(t.favorite?'★':'☆',()=>pref(!t.favorite,t.excluded),'secondary star'+(t.favorite?' on':'')),button(t.excluded?'Вернуть':'Исключить',()=>pref(t.favorite,!t.excluded)));row.append(check,body,controls);parent.append(row);}selectedCount();}
$('#search').oninput=renderMusic;$('#favorites').onchange=renderMusic;$('#select-visible').onclick=()=>{visibleMusic().filter(t=>!t.excluded).forEach(t=>selected.add(t.sha));renderMusic();};$('#clear-selection').onclick=()=>{selected.clear();renderMusic();};
function renderEpisodes(){const key=JSON.stringify(state.episodes);if(key===lastEpisodes)return;lastEpisodes=key;const parent=$('#episode-list');parent.replaceChildren();if(!state.episodes.length){parent.append(node('div','Здесь будут готовые выпуски.','empty'));return;}for(const e of state.episodes){const card=node('article',undefined,'card'),base='/media/episode/'+encodeURIComponent(e.name)+'/';const player=node(e.video?'video':'audio');player.controls=true;player.preload='none';player.src=base+(e.video?'episode.mp4':'mix.wav');card.append(player,node('h2',e.title),node('p',`${e.seconds?Math.round(e.seconds/60*10)/10+' минут · ':''}${e.name}`,'hint'));const links=node('div',undefined,'downloads');for(const [file,title] of [[e.video?'episode.mp4':'mix.wav','Скачать'],['tracklist.txt','Треклист']]){const a=node('a',title);a.href=base+file;a.download=file;links.append(a);}card.append(links);parent.append(card);}}
async function refresh(){try{const first=!state;state=await api('/api/state');$('#connection').textContent='● подключено';$('#disk').textContent=`Свободно на диске: ${state.free_gb} GB`;$('#queue-count').textContent=state.jobs.filter(j=>['queued','running'].includes(j.status)).length;$('#pause').textContent=state.paused?'Продолжить очередь':'Пауза после выпуска';$('#queue-hint').textContent=state.paused?'Очередь на паузе. Текущий выпуск, если есть, завершится.':'Одновременно работает один выпуск. При ошибке очередь автоматически приостановится.';if(first){options($('#style'),state.presets.styles,'morning');options($('#mood'),state.presets.moods,'calm');options($('#time-of-day'),state.presets.scenes,'morning');updateForm();}renderJobs();renderEpisodes();}catch(e){$('#connection').textContent='● нет связи';if(!state)notify(e.message);}}
async function poll(){await refresh();setTimeout(poll,4000);}poll();
